In [1]:
print ("Hello world!")

Hello world!


In [3]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
np.array([12,45,67,89,90])

array([12, 45, 67, 89, 90])

In [8]:
lst = [1,2,3,4,5,6]
lst

[1, 2, 3, 4, 5, 6]

In [9]:
type(lst)

list

In [11]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [13]:
arr = np.array(lst)
print(arr)

[1 2 3 4 5 6]


In [12]:
type(arr)

numpy.ndarray

In [15]:
arr.ndim

1

In [16]:
arr.shape

(6,)

In [ ]:
# Different between array and list

In [17]:
# diff 1

lst  = [12,3.56,67,78,'malay']
lst

[12, 3.56, 67, 78, 'malay']

In [20]:
arr = np.array([345.544,78,67,45,234])
print(arr)

[345.544  78.     67.     45.    234.   ]


In [21]:
# diff 2
arr = np.array([24,6,8]) * 2
arr

array([48, 12, 16])

In [22]:
# lst  = [2,4,6,8,10] * 2
# lst

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]

In [25]:
lst =  [2,4,6,8]
l= []
for i in lst:
  l.append(i*4)
l

[8, 16, 24, 32]

In [29]:
[i *4 for i in lst]

[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]

In [26]:
# diff 3

lst  =  list(range(1,100))
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
[i**2 for i in lst]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [35]:
%timeit [i**2 for i in lst]

3.04 µs ± 75 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
np.arange(1,100) **2

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

In [37]:
%timeit np.arange(1,100) **2

2.28 µs ± 570 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [38]:
# creation 1D 2D 3D array

In [39]:
# 1d
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [42]:
arr1.ndim

1

In [41]:
arr1.shape

(5,)

In [45]:
# 2d
arr2 = np.array([[1,2,3,4,5]])
arr2

array([[1, 2, 3, 4, 5]])

In [46]:
arr2.ndim

2

In [47]:
arr2.shape

(1, 5)

In [57]:
arr3 = np.array([[12,45,67],[78,67,45]])
arr3

array([[12, 45, 67],
       [78, 67, 45]])

In [59]:
arr3.ndim

2

In [60]:
arr3.shape

(2, 3)

In [62]:
#3d
arr4 = np.array([[[2,4,5,6],[34,67,89]]])
arr4

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.